name: Release CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          manifest-file: .release-please-manifest.json
          config-file: '.github/release-please-config.json'
